# Copyright 2021 Osico <http://osico.nl>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Hogerop all modules",
    "version": "14.0.0.0.0",
    "category": "Tools",
    "author": "Osico",
    "website": "https://osico.nl",
    "license": "AGPL-3",
    "summary": "Hogerop all modules",
    "depends": [
        'account',
#        'account_bank_statement_import',
#        'account_bank_statement_import_camt_oca',
        'account_banking_pain_base',
        'account_banking_sepa_credit_transfer',
#        'account_cancel',
        'account_financial_report',
#        'account_lock_to_date',
        'account_payment',
        'account_payment_mode',
        'account_payment_order',
        'account_payment_partner',
        'account_payment_purchase',
#        'account_payment_sale',
#        'account_tax_balance',
        'analytic',
        'auth_admin_passkey',
        'auth_signup',
        'barcodes',
        'base',
        'base_address_extended',
        'base_iban',
        'base_import',
        'base_setup',
        'base_vat',
        'bus',
        'calendar',
        'contacts',
        'crm',
#        'decimal_precision',
        'digest',
        'fetchmail',
        'hr',
        'hr_org_chart',
        'http_routing',
        'l10n_nl',
 #       'l10n_nl_bank',
        'l10n_nl_bsn',
 #       'l10n_nl_postcode',
 #       'l10n_nl_tax_invoice_basis',
        'l10n_nl_tax_statement',
#        'l10n_nl_tax_statement_icp',
  #      'l10n_nl_xaf_auditfile_export',
        'mail',
#        'mass_editing',
        'payment',
        'payment_transfer',
        'portal',
        'procurement_jit',
        'product',
        'purchase',
        'purchase_stock',
        'report_xlsx',
        'resource',
        'sale_management',
        'sale',
        'sale_purchase',
        'sale_stock',
        'sales_team',
        'stock',
        'stock_account',
        'uom',
        'utm',
        'web',
#        'web_diagram',
        'web_editor',
        'web_environment_ribbon',
        'web_kanban_gauge',
#        'web_settings_dashboard',
        'web_tour',
        'web_unsplash',
    ],
    "data": [],
    "installable": True,
}
